// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	chat.proto
	consensus.proto
	ledger.proto
	txmgr.proto

It has these top-level messages:
	Request
	Response
	ConsensusRequest
	ConsensusResponse
	BlocksRequest
	BlocksResponse
	BlockHeightRequest
	BlockHeightResponse
	TxPoolRequest
	TxPoolResponse
	CopyrightTxRequest
	CopyrightTxResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_Type int32

const (
	Request_CONSENSUS         Request_Type = 0
	Request_FETCH_BLOCKS      Request_Type = 1
	Request_FETCH_BLOCKHEIGHT Request_Type = 2
	Request_FETCH_TXPOOL      Request_Type = 3
	Request_COPYRIGHT_TX      Request_Type = 4
)

var Request_Type_name = map[int32]string{
	0: "CONSENSUS",
	1: "FETCH_BLOCKS",
	2: "FETCH_BLOCKHEIGHT",
	3: "FETCH_TXPOOL",
	4: "COPYRIGHT_TX",
}
var Request_Type_value = map[string]int32{
	"CONSENSUS":         0,
	"FETCH_BLOCKS":      1,
	"FETCH_BLOCKHEIGHT": 2,
	"FETCH_TXPOOL":      3,
	"COPYRIGHT_TX":      4,
}

func (x Request_Type) String() string {
	return proto1.EnumName(Request_Type_name, int32(x))
}
func (Request_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Response_Type int32

const (
	Response_CONSENSUS         Response_Type = 0
	Response_FETCH_BLOCKS      Response_Type = 1
	Response_FETCH_BLOCKHEIGHT Response_Type = 2
	Response_FETCH_TXPOOL      Response_Type = 3
	Response_COPYRIGHT_TX      Response_Type = 4
)

var Response_Type_name = map[int32]string{
	0: "CONSENSUS",
	1: "FETCH_BLOCKS",
	2: "FETCH_BLOCKHEIGHT",
	3: "FETCH_TXPOOL",
	4: "COPYRIGHT_TX",
}
var Response_Type_value = map[string]int32{
	"CONSENSUS":         0,
	"FETCH_BLOCKS":      1,
	"FETCH_BLOCKHEIGHT": 2,
	"FETCH_TXPOOL":      3,
	"COPYRIGHT_TX":      4,
}

func (x Response_Type) String() string {
	return proto1.EnumName(Response_Type_name, int32(x))
}
func (Response_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// 通信请求体
type Request struct {
	Type    Request_Type `protobuf:"varint,1,opt,name=type,enum=proto.Request_Type" json:"type,omitempty"`
	Payload []byte       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 通信响应体
type Response struct {
	Type    Response_Type `protobuf:"varint,1,opt,name=type,enum=proto.Response_Type" json:"type,omitempty"`
	Payload []byte        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*Request)(nil), "proto.Request")
	proto1.RegisterType((*Response)(nil), "proto.Response")
	proto1.RegisterEnum("proto.Request_Type", Request_Type_name, Request_Type_value)
	proto1.RegisterEnum("proto.Response_Type", Response_Type_name, Response_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Peer service

type PeerClient interface {
	// 封装rpc
	Chat(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type peerClient struct {
	cc *grpc.ClientConn
}

func NewPeerClient(cc *grpc.ClientConn) PeerClient {
	return &peerClient{cc}
}

func (c *peerClient) Chat(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.Peer/Chat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Peer service

type PeerServer interface {
	// 封装rpc
	Chat(context.Context, *Request) (*Response, error)
}

func RegisterPeerServer(s *grpc.Server, srv PeerServer) {
	s.RegisterService(&_Peer_serviceDesc, srv)
}

func _Peer_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Peer/Chat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).Chat(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Peer",
	HandlerType: (*PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _Peer_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x1b, 0x18, 0xb9, 0xd8, 0x83,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xd4, 0xb9, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x18,
	0x15, 0x18, 0x35, 0xf8, 0x8c, 0x84, 0x21, 0x0a, 0xf5, 0xa0, 0xb2, 0x7a, 0x21, 0x95, 0x05, 0xa9,
	0x41, 0x60, 0x05, 0x42, 0x12, 0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x30, 0xae, 0x52, 0x12, 0x17, 0x0b, 0x48, 0x9d, 0x10, 0x2f, 0x17,
	0xa7, 0xb3, 0xbf, 0x5f, 0xb0, 0xab, 0x5f, 0x70, 0x68, 0xb0, 0x00, 0x83, 0x90, 0x00, 0x17, 0x8f,
	0x9b, 0x6b, 0x88, 0xb3, 0x47, 0xbc, 0x93, 0x8f, 0xbf, 0xb3, 0x77, 0xb0, 0x00, 0xa3, 0x90, 0x28,
	0x97, 0x20, 0x92, 0x88, 0x87, 0xab, 0xa7, 0xbb, 0x47, 0x88, 0x00, 0x13, 0x42, 0x61, 0x48, 0x44,
	0x80, 0xbf, 0xbf, 0x8f, 0x00, 0x33, 0x48, 0xc4, 0xd9, 0x3f, 0x20, 0x32, 0x08, 0xa4, 0x20, 0x3e,
	0x24, 0x42, 0x80, 0x45, 0x69, 0x13, 0x23, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71,
	0xaa, 0x90, 0x06, 0x8a, 0x9b, 0x45, 0xe0, 0x6e, 0x86, 0x48, 0x0f, 0x1a, 0x47, 0x1b, 0x19, 0x72,
	0xb1, 0x04, 0xa4, 0xa6, 0x16, 0x09, 0x69, 0x72, 0xb1, 0x38, 0x67, 0x24, 0x96, 0x08, 0xf1, 0xa1,
	0x86, 0xae, 0x14, 0x3f, 0x9a, 0xcb, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x22, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x68, 0xa6, 0x43, 0x42, 0xb6, 0x01, 0x00, 0x00,
}
