// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Get blocks
type BlocksRequest struct {
	BlocksNum uint64 `protobuf:"varint,1,opt,name=BlocksNum" json:"BlocksNum,omitempty"`
}

func (m *BlocksRequest) Reset()                    { *m = BlocksRequest{} }
func (m *BlocksRequest) String() string            { return proto1.CompactTextString(m) }
func (*BlocksRequest) ProtoMessage()               {}
func (*BlocksRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *BlocksRequest) GetBlocksNum() uint64 {
	if m != nil {
		return m.BlocksNum
	}
	return 0
}

type BlocksResponse struct {
	Payload []byte `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (m *BlocksResponse) Reset()                    { *m = BlocksResponse{} }
func (m *BlocksResponse) String() string            { return proto1.CompactTextString(m) }
func (*BlocksResponse) ProtoMessage()               {}
func (*BlocksResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *BlocksResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type BlockHeightRequest struct {
}

func (m *BlockHeightRequest) Reset()                    { *m = BlockHeightRequest{} }
func (m *BlockHeightRequest) String() string            { return proto1.CompactTextString(m) }
func (*BlockHeightRequest) ProtoMessage()               {}
func (*BlockHeightRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type BlockHeightResponse struct {
	BlockHeight uint64 `protobuf:"varint,1,opt,name=BlockHeight" json:"BlockHeight,omitempty"`
}

func (m *BlockHeightResponse) Reset()                    { *m = BlockHeightResponse{} }
func (m *BlockHeightResponse) String() string            { return proto1.CompactTextString(m) }
func (*BlockHeightResponse) ProtoMessage()               {}
func (*BlockHeightResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *BlockHeightResponse) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type TxPoolRequest struct {
}

func (m *TxPoolRequest) Reset()                    { *m = TxPoolRequest{} }
func (m *TxPoolRequest) String() string            { return proto1.CompactTextString(m) }
func (*TxPoolRequest) ProtoMessage()               {}
func (*TxPoolRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

type TxPoolResponse struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *TxPoolResponse) Reset()                    { *m = TxPoolResponse{} }
func (m *TxPoolResponse) String() string            { return proto1.CompactTextString(m) }
func (*TxPoolResponse) ProtoMessage()               {}
func (*TxPoolResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *TxPoolResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto1.RegisterType((*BlocksRequest)(nil), "proto.BlocksRequest")
	proto1.RegisterType((*BlocksResponse)(nil), "proto.BlocksResponse")
	proto1.RegisterType((*BlockHeightRequest)(nil), "proto.BlockHeightRequest")
	proto1.RegisterType((*BlockHeightResponse)(nil), "proto.BlockHeightResponse")
	proto1.RegisterType((*TxPoolRequest)(nil), "proto.TxPoolRequest")
	proto1.RegisterType((*TxPoolResponse)(nil), "proto.TxPoolResponse")
}

func init() { proto1.RegisterFile("ledger.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x49, 0x4d, 0x49,
	0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xba, 0x5c, 0xbc,
	0x4e, 0x39, 0xf9, 0xc9, 0xd9, 0xc5, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x32, 0x5c,
	0x9c, 0x10, 0x01, 0xbf, 0xd2, 0x5c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x84, 0x80, 0x92,
	0x16, 0x17, 0x1f, 0x4c, 0x79, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x04, 0x17, 0x7b, 0x40,
	0x62, 0x65, 0x4e, 0x7e, 0x62, 0x0a, 0x58, 0x35, 0x4f, 0x10, 0x8c, 0xab, 0x24, 0xc2, 0x25, 0x04,
	0x56, 0xeb, 0x91, 0x9a, 0x99, 0x9e, 0x51, 0x02, 0x35, 0x5f, 0xc9, 0x9c, 0x4b, 0x18, 0x45, 0x14,
	0x6a, 0x8c, 0x02, 0x17, 0x37, 0x92, 0x30, 0xd4, 0x62, 0x64, 0x21, 0x25, 0x7e, 0x2e, 0xde, 0x90,
	0x8a, 0x80, 0xfc, 0xfc, 0x1c, 0x98, 0x49, 0x5a, 0x5c, 0x7c, 0x30, 0x01, 0x84, 0x5b, 0x0a, 0x50,
	0xdd, 0x02, 0xe5, 0x26, 0xb1, 0x81, 0x7d, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x14,
	0x00, 0x4c, 0x04, 0x01, 0x00, 0x00,
}
