// Code generated by protoc-gen-go.
// source: txmgr.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	txmgr.proto

It has these top-level messages:
	CopyrightTxRequest
	CopyrightTxResponse
	WorkPutTxRequest
	WorkPutTxResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// transaction request body.
type CopyrightTxRequest struct {
	SessionID string `protobuf:"bytes,1,opt,name=SessionID" json:"SessionID,omitempty"`
	WorkID    string `protobuf:"bytes,2,opt,name=WorkID" json:"WorkID,omitempty"`
	From      string `protobuf:"bytes,3,opt,name=From" json:"From,omitempty"`
	To        string `protobuf:"bytes,4,opt,name=To" json:"To,omitempty"`
}

func (m *CopyrightTxRequest) Reset()                    { *m = CopyrightTxRequest{} }
func (m *CopyrightTxRequest) String() string            { return proto1.CompactTextString(m) }
func (*CopyrightTxRequest) ProtoMessage()               {}
func (*CopyrightTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// transaction response body.
type CopyrightTxResponse struct {
}

func (m *CopyrightTxResponse) Reset()                    { *m = CopyrightTxResponse{} }
func (m *CopyrightTxResponse) String() string            { return proto1.CompactTextString(m) }
func (*CopyrightTxResponse) ProtoMessage()               {}
func (*CopyrightTxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// transaction request body.
type WorkPutTxRequest struct {
	SessionID string `protobuf:"bytes,1,opt,name=SessionID" json:"SessionID,omitempty"`
	WorkName  string `protobuf:"bytes,2,opt,name=WorkName" json:"WorkName,omitempty"`
	Owner     string `protobuf:"bytes,3,opt,name=Owner" json:"Owner,omitempty"`
	Admin     string `protobuf:"bytes,4,opt,name=Admin" json:"Admin,omitempty"`
	Timestamp string `protobuf:"bytes,5,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *WorkPutTxRequest) Reset()                    { *m = WorkPutTxRequest{} }
func (m *WorkPutTxRequest) String() string            { return proto1.CompactTextString(m) }
func (*WorkPutTxRequest) ProtoMessage()               {}
func (*WorkPutTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// transaction response body.
type WorkPutTxResponse struct {
}

func (m *WorkPutTxResponse) Reset()                    { *m = WorkPutTxResponse{} }
func (m *WorkPutTxResponse) String() string            { return proto1.CompactTextString(m) }
func (*WorkPutTxResponse) ProtoMessage()               {}
func (*WorkPutTxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto1.RegisterType((*CopyrightTxRequest)(nil), "proto.CopyrightTxRequest")
	proto1.RegisterType((*CopyrightTxResponse)(nil), "proto.CopyrightTxResponse")
	proto1.RegisterType((*WorkPutTxRequest)(nil), "proto.WorkPutTxRequest")
	proto1.RegisterType((*WorkPutTxResponse)(nil), "proto.WorkPutTxResponse")
}

func init() { proto1.RegisterFile("txmgr.proto", fileDescriptor0) }

var fileDescriptor3 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0xc8, 0x4d,
	0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x79, 0x5c, 0x42, 0xce,
	0xf9, 0x05, 0x95, 0x45, 0x99, 0xe9, 0x19, 0x25, 0x21, 0x15, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x32, 0x5c, 0x9c, 0xc1, 0xa9, 0xc5, 0xc5, 0x99, 0xf9, 0x79, 0x9e, 0x2e, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x21, 0x31, 0x2e, 0xb6, 0xf0, 0xfc, 0xa2, 0x6c, 0x4f,
	0x17, 0x09, 0x26, 0xb0, 0x14, 0x94, 0x27, 0x24, 0xc4, 0xc5, 0xe2, 0x56, 0x94, 0x9f, 0x2b, 0xc1,
	0x0c, 0x16, 0x05, 0xb3, 0x85, 0xf8, 0xb8, 0x98, 0x42, 0xf2, 0x25, 0x58, 0xc0, 0x22, 0x4c, 0x21,
	0xf9, 0x4a, 0xa2, 0x5c, 0xc2, 0x28, 0xf6, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0x4d, 0x63,
	0xe4, 0x12, 0x00, 0x99, 0x12, 0x50, 0x4a, 0xb4, 0x2b, 0xa4, 0xb8, 0x38, 0x40, 0x3a, 0xfc, 0x12,
	0x73, 0x53, 0xa1, 0xee, 0x80, 0xf3, 0x85, 0x44, 0xb8, 0x58, 0xfd, 0xcb, 0xf3, 0x52, 0x8b, 0xa0,
	0x4e, 0x81, 0x70, 0x40, 0xa2, 0x8e, 0x29, 0xb9, 0x99, 0x79, 0x50, 0xe7, 0x40, 0x38, 0x20, 0x5b,
	0x42, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x24, 0x58, 0x21, 0xb6, 0xc0, 0x05, 0x94,
	0x84, 0xb9, 0x04, 0x91, 0xdc, 0x05, 0x71, 0x6d, 0x12, 0x1b, 0x38, 0xec, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xfc, 0xde, 0x55, 0xcf, 0x51, 0x01, 0x00, 0x00,
}
